SUMMARY = "Virtual Python Environment builder"
DESCRIPTION = "\
virtualenv is a tool to create isolated Python environments."
HOMEPAGE = "https://pypi.python.org/pypi/virtualenv/"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://${COREBASE}/meta/COPYING.MIT;md5=3da9cfbcb788c80a0384361b4de20420"
SRC_URI[md5sum] = 1ed3fb292c672b852195ea75ff812bec""
SRC_URI[sha256sum] = "0d62c70883c0342d59c11d0ddac0d954d0431321a41ab20851facf2b222598f3"

PYPI_PACKAGE = "virtualenv"
