SUMMARY = "Virtual Python Environment builder"
DESCRIPTION = "\
virtualenv is a tool to create isolated Python environments."
HOMEPAGE = "https://pypi.python.org/pypi/virtualenv/"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://${COREBASE}/meta/COPYING.MIT;md5=3da9cfbcb788c80a0384361b4de20420"
SRC_URI[md5sum] = "2132afa3012afb599b00bcc628b0c99f"
SRC_URI[sha256sum] = "d257bb3773e48cac60e475a19b608996c73f4d333b3ba2e4e57d5ac6134e0136"

PYPI_PACKAGE = "virtualenv"
