SUMMARY = "esptool is A command line utility to flash firmware for ESP8266 & ESP32 "
DESCRIPTION = "\
A command line utility to communicate with the ROM bootloader in Espressif ESP8266 & ESP32 microcontrollers.\
Allows flashing firmware, reading back firmware, querying chip parameters, etc.\
The esptool.py project is hosted on github: https://github.com/espressif/esptool\
"
HOMEPAGE = "https://github.com/espressif/esptool"
LICENSE = "BSD"
LIC_FILES_CHKSUM = "file://LICENSE;md5=b234ee4d69f5fce4486a80fdaf4a4263"

SRC_URI[md5sum] = "17853949fd582550a7c270f08d7691d4"
SRC_URI[sha256sum] = "549ef93eef42ee7e9462ce5a53c16df7a0c71d91b3f77e19ec15749804cdf300"

PYPI_PACKAGE = "esptool"
