SUMMARY = "Virtual Python Environment builder"
DESCRIPTION = "\
virtualenv is a tool to create isolated Python environments."
HOMEPAGE = "https://pypi.python.org/pypi/virtualenv/"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://${COREBASE}/meta/COPYING.MIT;md5=3da9cfbcb788c80a0384361b4de20420"
SRC_URI[md5sum] = "44e19f4134906fe2d75124427dc9b716"
SRC_URI[sha256sum] = "02f8102c2436bb03b3ee6dede1919d1dac8a427541652e5ec95171ec8adbc93a"

PYPI_PACKAGE = "virtualenv"

